<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [5]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice *s.exchangerate)) AS median_sales
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales
0                          Audio        219.59
1        Cameras and camcorders         730.74
2                    Cell phones        459.88
3                      Computers        982.44
4                 Games and Toys         34.10
5                Home Appliances        696.08
6  Music, Movies and Audio Books        152.80
7                   TV and Video        682.83

In [12]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (
  ORDER BY
  (CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END)
  ) AS median_sales_2022
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales_2022
0                          Audio             257.21
1        Cameras and camcorders              651.46
2                    Cell phones             418.60
3                      Computers             809.70
4                 Games and Toys              33.78
5                Home Appliances             791.00
6  Music, Movies and Audio Books             186.58
7                   TV and Video             730.46

In [30]:
%%sql

WITH median_value AS (
  SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM sales s
)

SELECT
  p.categoryname AS category,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
  AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
  AND s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2022,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) < mv.median
  AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS low_net_revenue_2023,
  SUM(CASE WHEN (s.quantity * s.netprice * s.exchangerate) >= mv.median
  AND s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
  THEN (s.quantity * s.netprice * s.exchangerate) END) AS high_net_revenue_2023 -- 计算高于中位数的的销售总额
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  median_value mv -- 子查询
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,223932.63,543005.58,181847.01,506843.18
1,Cameras and camcorders,133801.07,2248731.49,105268.50,1878277.79
2,Cell phones,822810.73,7296854.34,738857.59,5263290.05
3,Computers,626333.55,17235879.94,592385.19,11058482.02
4,Games and Toys,232378.35,83748.95,206103.36,64271.60
5,Home Appliances,220196.04,6392250.64,177059.16,5742933.71
6,"Music, Movies and Audio Books",687403.38,2301893.90,576552.89,1604215.24
7,TV and Video,273532.94,5541803.66,166265.95,4245912.27

In [45]:
%%sql

WITH perc_group AS (
  SELECT
    PERCENTILE_CONT(0.25) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS low_perc,
    PERCENTILE_CONT(0.75) WITHIN GROUP
    (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS high_perc
  FROM sales s
  WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)

SELECT
  p.categoryname AS category,
  CASE
    WHEN (s.quantity * s.netprice * s.exchangerate) <= perc.low_perc THEN '1-LOW'
    WHEN (s.quantity * s.netprice * s.exchangerate) >= perc.high_perc THEN '3-HIGH'
    ELSE '2-MEDIAM' END AS revenue_tier,
  SUM(s.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM
  sales s
  LEFT JOIN product p ON s.productkey = p.productkey,
  perc_group perc -- 子查询
GROUP BY p.categoryname,revenue_tier
ORDER BY p.categoryname
-- 将销售额按高低排序后，根据在所有数据中的占比分类

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category revenue_tier  total_revenue
0                           Audio        1-LOW      267217.01
1                           Audio     2-MEDIAM     3832415.38
2                           Audio       3-HIGH     1213265.71
3         Cameras and camcorders         1-LOW       81032.92
4         Cameras and camcorders      2-MEDIAM     3388546.10
5         Cameras and camcorders        3-HIGH    15050781.63
6                     Cell phones        1-LOW      410309.35
7                     Cell phones     2-MEDIAM    10338963.22
8                     Cell phones       3-HIGH    21874993.15
9                       Computers        1-LOW      203207.06
10                      Computers     2-MEDIAM    10808054.11
11                      Computers       3-HIGH    79607760.89
12                 Games and Toys        1-LOW      533443.13
13                 Games and Toys     2-MEDIAM     1001381.91
14                 Games and Toys       3-HIGH      133749.09
15                Home Appliances        1-LOW      105045.60
16                Home Appliances     2-MEDIAM     4118724.64
17                Home Appliances       3-HIGH    22383475.30
18  Music, Movies and Audio Books        1-LOW      642496.71
19  Music, Movies and Audio Books     2-MEDIAM     6100817.99
20  Music, Movies and Audio Books       3-HIGH     3844996.29
21                   TV and Video        1-LOW       67221.76
22                   TV and Video     2-MEDIAM     3766783.30
23                   TV and Video       3-HIGH    16632856.33

In [ ]:
%%sql

SELECT
  orderdate,
  DATE_TRUNC('month',orderdate)::date AS order_month
   -- 将符合条件的日期按时间戳的方式显示，::date表示将时间戳转为日期格式
FROM sales
ORDER BY RANDOM()
LIMIT 10

In [52]:
%%sql

SELECT
  EXTRACT('year' FROM orderdate) AS order_date_yearly,
  EXTRACT('month' FROM orderdate) AS order_date_monthly,
  SUM(quantity * netprice * exchangerate) AS total_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
   -- 将符合条件的日期按时间戳的方式显示，::date表示将时间戳转为日期格式
  -- DATE_PART('year',orderdate) -- 将日期的年、月、日提取出来，转为小数
  -- EXTRACT('year' FROM orderdate) -- 将日期的年、月、日提取出来,转为字符串
FROM sales
GROUP BY order_date_yearly,order_date_monthly
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_date_yearly order_date_monthly  total_revenue  total_unique_customers
0              2015                  1      384092.66                     200
1              2015                  2      706374.12                     291
2              2015                  3      332961.59                     139
3              2015                  4      160767.00                      78
4              2015                  5      548632.63                     236
5              2015                  6      748563.97                     238
6              2015                  7      635376.13                     227
7              2015                  8      718538.62                     235
8              2015                  9      696805.68                     277
9              2015                 10      824891.22                     304

In [ ]:
%%sql

SELECT
  CURRENT_DATE,
  orderdate
  -- INTERVAL '5 years' 显示5年间隔的时间
FROM sales
WHERE orderdate >= CURRENT_DATE - INTERVAL '5 years' -- 查找近5年的数据
LIMIT 10